
package com.mycompany.metro;

import java.awt.CardLayout;
import java.awt.Color;

public class DataEntryOperatorScreen extends javax.swing.JFrame {

    /**
     * Creates new form DataEntryOperatorScreen
     */
    public DataEntryOperatorScreen() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LeftPanel = new javax.swing.JPanel();
        OldVendorBtn = new javax.swing.JButton();
        NewVendorBtn = new javax.swing.JButton();
        ChangePasswordBtn = new javax.swing.JButton();
        LogOutBtn = new javax.swing.JButton();
        RightPanel = new javax.swing.JPanel();
        OldVendorPanel = new javax.swing.JPanel();
        SystemNameLb = new javax.swing.JLabel();
        SloganLb = new javax.swing.JLabel();
        OldVendorNavLb = new javax.swing.JLabel();
        NewVendorPanel = new javax.swing.JPanel();
        SystemNameLb1 = new javax.swing.JLabel();
        SloganLb1 = new javax.swing.JLabel();
        NewVendorNavLb = new javax.swing.JLabel();
        ChangePasswordPanel = new javax.swing.JPanel();
        SystemNameLb2 = new javax.swing.JLabel();
        SloganLb2 = new javax.swing.JLabel();
        ChangePasswordLbNav = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("METRO - Data Entry Operator Menu");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LeftPanel.setBackground(new java.awt.Color(1, 146, 213));
        LeftPanel.setPreferredSize(new java.awt.Dimension(300, 1024));

        OldVendorBtn.setBackground(new java.awt.Color(1, 146, 213));
        OldVendorBtn.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        OldVendorBtn.setForeground(new java.awt.Color(255, 255, 255));
        OldVendorBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\it\\Downloads\\oldVendor.png")); // NOI18N
        OldVendorBtn.setText("View Old Vendors");
        OldVendorBtn.setBorder(null);
        OldVendorBtn.setBorderPainted(false);
        OldVendorBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OldVendorBtn.setFocusPainted(false);
        OldVendorBtn.setPreferredSize(new java.awt.Dimension(300, 90));
        OldVendorBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OldVendorBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OldVendorBtnMouseExited(evt);
            }
        });
        OldVendorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OldVendorBtnActionPerformed(evt);
            }
        });

        NewVendorBtn.setBackground(new java.awt.Color(1, 146, 213));
        NewVendorBtn.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        NewVendorBtn.setForeground(new java.awt.Color(255, 255, 255));
        NewVendorBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\it\\Downloads\\newVendor.png")); // NOI18N
        NewVendorBtn.setText("Add New Vendors");
        NewVendorBtn.setBorderPainted(false);
        NewVendorBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NewVendorBtn.setFocusPainted(false);
        NewVendorBtn.setPreferredSize(new java.awt.Dimension(300, 90));
        NewVendorBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NewVendorBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NewVendorBtnMouseExited(evt);
            }
        });
        NewVendorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewVendorBtnActionPerformed(evt);
            }
        });

        ChangePasswordBtn.setBackground(new java.awt.Color(1, 146, 213));
        ChangePasswordBtn.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        ChangePasswordBtn.setForeground(new java.awt.Color(255, 255, 255));
        ChangePasswordBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\it\\Downloads\\changePassword.png")); // NOI18N
        ChangePasswordBtn.setText("  Change Password");
        ChangePasswordBtn.setBorderPainted(false);
        ChangePasswordBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ChangePasswordBtn.setFocusPainted(false);
        ChangePasswordBtn.setPreferredSize(new java.awt.Dimension(300, 90));
        ChangePasswordBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ChangePasswordBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ChangePasswordBtnMouseExited(evt);
            }
        });
        ChangePasswordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangePasswordBtnActionPerformed(evt);
            }
        });

        LogOutBtn.setBackground(new java.awt.Color(1, 146, 213));
        LogOutBtn.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        LogOutBtn.setForeground(new java.awt.Color(255, 255, 255));
        LogOutBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\it\\Downloads\\logOut.png")); // NOI18N
        LogOutBtn.setText("  Log Out");
        LogOutBtn.setToolTipText("");
        LogOutBtn.setPreferredSize(new java.awt.Dimension(120, 45));
        LogOutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogOutBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogOutBtnMouseExited(evt);
            }
        });
        LogOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LeftPanelLayout = new javax.swing.GroupLayout(LeftPanel);
        LeftPanel.setLayout(LeftPanelLayout);
        LeftPanelLayout.setHorizontalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftPanelLayout.createSequentialGroup()
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OldVendorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewVendorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChangePasswordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(LeftPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(LogOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LeftPanelLayout.setVerticalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftPanelLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(OldVendorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NewVendorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(ChangePasswordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 437, Short.MAX_VALUE)
                .addComponent(LogOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        getContentPane().add(LeftPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        RightPanel.setBackground(new java.awt.Color(255, 255, 255));
        RightPanel.setPreferredSize(new java.awt.Dimension(980, 1024));
        RightPanel.setLayout(new java.awt.CardLayout());

        OldVendorPanel.setBackground(new java.awt.Color(255, 255, 255));

        SystemNameLb.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        SystemNameLb.setForeground(new java.awt.Color(51, 51, 51));
        SystemNameLb.setText("Metro Point of Sale System");

        SloganLb.setFont(new java.awt.Font("Century Gothic", 2, 24)); // NOI18N
        SloganLb.setForeground(new java.awt.Color(51, 51, 51));
        SloganLb.setText("Lets Make this day Productive, John!");

        OldVendorNavLb.setFont(new java.awt.Font("Century Schoolbook", 2, 20)); // NOI18N
        OldVendorNavLb.setForeground(new java.awt.Color(153, 153, 255));
        OldVendorNavLb.setText("Old Vendors Window");

        javax.swing.GroupLayout OldVendorPanelLayout = new javax.swing.GroupLayout(OldVendorPanel);
        OldVendorPanel.setLayout(OldVendorPanelLayout);
        OldVendorPanelLayout.setHorizontalGroup(
            OldVendorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OldVendorPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(OldVendorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SloganLb)
                    .addGroup(OldVendorPanelLayout.createSequentialGroup()
                        .addComponent(SystemNameLb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 274, Short.MAX_VALUE)
                        .addComponent(OldVendorNavLb)))
                .addContainerGap())
        );
        OldVendorPanelLayout.setVerticalGroup(
            OldVendorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OldVendorPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(OldVendorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SystemNameLb)
                    .addGroup(OldVendorPanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(OldVendorNavLb)))
                .addGap(28, 28, 28)
                .addComponent(SloganLb)
                .addContainerGap(894, Short.MAX_VALUE))
        );

        RightPanel.add(OldVendorPanel, "card2");

        NewVendorPanel.setBackground(new java.awt.Color(255, 255, 255));

        SystemNameLb1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        SystemNameLb1.setForeground(new java.awt.Color(51, 51, 51));
        SystemNameLb1.setText("Metro Point of Sale System");

        SloganLb1.setFont(new java.awt.Font("Century Gothic", 2, 24)); // NOI18N
        SloganLb1.setForeground(new java.awt.Color(51, 51, 51));
        SloganLb1.setText("Lets Make this day Productive, John!");

        NewVendorNavLb.setFont(new java.awt.Font("Century Schoolbook", 2, 20)); // NOI18N
        NewVendorNavLb.setForeground(new java.awt.Color(153, 153, 255));
        NewVendorNavLb.setText("New Vendor Window");

        javax.swing.GroupLayout NewVendorPanelLayout = new javax.swing.GroupLayout(NewVendorPanel);
        NewVendorPanel.setLayout(NewVendorPanelLayout);
        NewVendorPanelLayout.setHorizontalGroup(
            NewVendorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewVendorPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(NewVendorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NewVendorPanelLayout.createSequentialGroup()
                        .addComponent(SloganLb1)
                        .addContainerGap(505, Short.MAX_VALUE))
                    .addGroup(NewVendorPanelLayout.createSequentialGroup()
                        .addComponent(SystemNameLb1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NewVendorNavLb)
                        .addGap(14, 14, 14))))
        );
        NewVendorPanelLayout.setVerticalGroup(
            NewVendorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewVendorPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(NewVendorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SystemNameLb1)
                    .addGroup(NewVendorPanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(NewVendorNavLb)))
                .addGap(28, 28, 28)
                .addComponent(SloganLb1)
                .addContainerGap(894, Short.MAX_VALUE))
        );

        RightPanel.add(NewVendorPanel, "card3");

        ChangePasswordPanel.setBackground(new java.awt.Color(255, 255, 255));

        SystemNameLb2.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        SystemNameLb2.setForeground(new java.awt.Color(51, 51, 51));
        SystemNameLb2.setText("Metro Point of Sale System");

        SloganLb2.setFont(new java.awt.Font("Century Gothic", 2, 24)); // NOI18N
        SloganLb2.setForeground(new java.awt.Color(51, 51, 51));
        SloganLb2.setText("Lets Make the digital world Strong, John!");

        ChangePasswordLbNav.setFont(new java.awt.Font("Century Schoolbook", 2, 20)); // NOI18N
        ChangePasswordLbNav.setForeground(new java.awt.Color(153, 153, 255));
        ChangePasswordLbNav.setText("Change Password Window");

        javax.swing.GroupLayout ChangePasswordPanelLayout = new javax.swing.GroupLayout(ChangePasswordPanel);
        ChangePasswordPanel.setLayout(ChangePasswordPanelLayout);
        ChangePasswordPanelLayout.setHorizontalGroup(
            ChangePasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChangePasswordPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(ChangePasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ChangePasswordPanelLayout.createSequentialGroup()
                        .addComponent(SloganLb2)
                        .addContainerGap(454, Short.MAX_VALUE))
                    .addGroup(ChangePasswordPanelLayout.createSequentialGroup()
                        .addComponent(SystemNameLb2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ChangePasswordLbNav)
                        .addGap(16, 16, 16))))
        );
        ChangePasswordPanelLayout.setVerticalGroup(
            ChangePasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChangePasswordPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(ChangePasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SystemNameLb2)
                    .addGroup(ChangePasswordPanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(ChangePasswordLbNav)))
                .addGap(28, 28, 28)
                .addComponent(SloganLb2)
                .addContainerGap(894, Short.MAX_VALUE))
        );

        RightPanel.add(ChangePasswordPanel, "card4");

        getContentPane().add(RightPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

     // Method to show OldVendorPanel
    private void showOldVendorPanel() {
        OldVendorPanel.setVisible(true);
        NewVendorPanel.setVisible(false);
        ChangePasswordPanel.setVisible(false);
    }

    // Method to show NewVendorPanel
    private void showNewVendorPanel() {
        OldVendorPanel.setVisible(false);
        NewVendorPanel.setVisible(true);
        ChangePasswordPanel.setVisible(false);
    }

    // Method to show ChangePasswordPanel
    private void showChangePasswordPanel() {
        OldVendorPanel.setVisible(false);
        NewVendorPanel.setVisible(false);
        ChangePasswordPanel.setVisible(true);
    }
    
    private void OldVendorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OldVendorBtnActionPerformed
      showOldVendorPanel();
    }//GEN-LAST:event_OldVendorBtnActionPerformed

    private void NewVendorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewVendorBtnActionPerformed
         showNewVendorPanel();
    }//GEN-LAST:event_NewVendorBtnActionPerformed

    private void ChangePasswordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangePasswordBtnActionPerformed
        showChangePasswordPanel();
    }//GEN-LAST:event_ChangePasswordBtnActionPerformed

    private void LogOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutBtnActionPerformed
        dispose();
    }//GEN-LAST:event_LogOutBtnActionPerformed

    private void OldVendorBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OldVendorBtnMouseEntered
         OldVendorBtn.setBackground(new Color(34, 103, 176));
    }//GEN-LAST:event_OldVendorBtnMouseEntered

    private void OldVendorBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OldVendorBtnMouseExited
         OldVendorBtn.setBackground(new Color(1, 146, 213));
    }//GEN-LAST:event_OldVendorBtnMouseExited

    private void NewVendorBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewVendorBtnMouseEntered
        NewVendorBtn.setBackground(new Color(34, 103, 176));
    }//GEN-LAST:event_NewVendorBtnMouseEntered

    private void NewVendorBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewVendorBtnMouseExited
        NewVendorBtn.setBackground(new Color(1, 146, 213));
    }//GEN-LAST:event_NewVendorBtnMouseExited

    private void ChangePasswordBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangePasswordBtnMouseEntered
        ChangePasswordBtn.setBackground(new Color(34, 103, 176));
    }//GEN-LAST:event_ChangePasswordBtnMouseEntered

    private void ChangePasswordBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangePasswordBtnMouseExited
     ChangePasswordBtn.setBackground(new Color(1, 146, 213));
    }//GEN-LAST:event_ChangePasswordBtnMouseExited

    private void LogOutBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutBtnMouseEntered
        LogOutBtn.setBackground(new Color(255, 192, 192));
        LogOutBtn.setForeground(Color.BLACK);
    }//GEN-LAST:event_LogOutBtnMouseEntered

    private void LogOutBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutBtnMouseExited
        LogOutBtn.setBackground(new Color(1, 146, 213));
    }//GEN-LAST:event_LogOutBtnMouseExited

    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataEntryOperatorScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataEntryOperatorScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataEntryOperatorScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataEntryOperatorScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataEntryOperatorScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChangePasswordBtn;
    private javax.swing.JLabel ChangePasswordLbNav;
    private javax.swing.JPanel ChangePasswordPanel;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JButton LogOutBtn;
    private javax.swing.JButton NewVendorBtn;
    private javax.swing.JLabel NewVendorNavLb;
    private javax.swing.JPanel NewVendorPanel;
    private javax.swing.JButton OldVendorBtn;
    private javax.swing.JLabel OldVendorNavLb;
    private javax.swing.JPanel OldVendorPanel;
    private javax.swing.JPanel RightPanel;
    private javax.swing.JLabel SloganLb;
    private javax.swing.JLabel SloganLb1;
    private javax.swing.JLabel SloganLb2;
    private javax.swing.JLabel SystemNameLb;
    private javax.swing.JLabel SystemNameLb1;
    private javax.swing.JLabel SystemNameLb2;
    // End of variables declaration//GEN-END:variables
}
